### ISSUE TITLE
Fix fork issues

### ISSUE THREAD

**Issue by surli** [Spirals-Team/repairnator#435]
See the following stack, even if no push URL is given:

11:17:00.162 [main] INFO  f.i.s.r.p.step.push.CommitPatch - Fork the repository: surli/failingProject
11:17:00.444 [main] ERROR f.i.s.r.p.step.push.CommitPatch - Error while forking the repository surli/failingProject
java.io.FileNotFoundException: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/forks/#create-a-fork"}
        at org.kohsuke.github.Requester.handleApiError(Requester.java:650)
        at org.kohsuke.github.Requester._to(Requester.java:283)
        at org.kohsuke.github.Requester.to(Requester.java:224)
        at org.kohsuke.github.GHRepository.fork(GHRepository.java:637)
        at fr.inria.spirals.repairnator.process.git.GitHelper.forkRepository(GitHelper.java:356)
        at fr.inria.spirals.repairnator.process.step.AbstractStep.observeAndNotify(AbstractStep.java:186)

**Comment by surli** [comment]
Fixed with #437
