### ISSUE TITLE
AssertFixer: TestListener.ser file not found

### ISSUE THREAD

**Issue by surli** [Spirals-Team/repairnator#544]
We still have issues with AssertFixer:

```
16:48:16.134 [main] INFO  f.i.s.r.p.s.repair.AssertFixerRepair - Start AssertFixerRepair
16:48:16.144 [main] INFO  f.i.s.r.p.s.repair.AssertFixerRepair - Launcher AssertFixer with the following configuration: {
  "classpath": "/root/workspace/Innovimax-SARL/mix-them/377763597/target/classes/:/root/workspace/Innovimax-SARL/mix-them/377763597/target/test-classes/:/root/./workspace/Innovimax-SARL/mix-them/377763597/.m2/junit/junit/4.12/junit-4.12.jar:/root/./workspace/Innovimax-SARL/mix-them/377763597/.m2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar",
  "pathToSourceFolder": [
    "/root/workspace/Innovimax-SARL/mix-them/377763597/src/main/java"
  ],
  "pathToTestFolder": [
    "/root/./workspace/Innovimax-SARL/mix-them/377763597/src/test/java"
  ],
  "verbose": true,
  "output": "/tmp/1526050096142-0",
  "multipleTestCases": {
    "innovimax.mixthem.GenericTest": [
      "testCharRules"
    ]
  }
}
16:48:20.692 [pool-3-thread-1] INFO  e.s.project.testrunner.EntryPoint - Run: java -cp /tmp/1526050096142-0/spooned-classes/:/root/workspace/Innovimax-SARL/mix-them/377763597/target/classes/:/root/workspace/Innovimax-SARL/mix-them/377763597/target/test-classes/:/root/./workspace/Innovimax-SARL/mix-them/377763597/.m2/junit/junit/4.12/junit-4.12.jar:/root/./workspace/Innovimax-SARL/mix-them/377763597/.m2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/root/repairnator-pipeline.jar eu.stamp.project.testrunner.runner.test.TestRunner innovimax.mixthem.GenericTest testCharRules
16:48:21.815 [pool-3-thread-1] ERROR f.i.s.r.p.s.repair.AssertFixerRepair - Got exception when running AssertFixer: 
java.lang.RuntimeException: java.io.FileNotFoundException: /root/target/dspot/TestListener.ser does not exist.
        at eu.stamp.project.testrunner.runner.test.Loader.load(Loader.java:20)
        at eu.stamp.project.testrunner.runner.test.TestListener.load(TestListener.java:137)
        at eu.stamp.project.testrunner.EntryPoint.runTests(EntryPoint.java:129)
        at eu.stamp.project.testrunner.EntryPoint.runTests(EntryPoint.java:111)
        at eu.stamp.project.assertfixer.test.TestRunner.runTest(TestRunner.java:44)
        at eu.stamp.project.assertfixer.Main.fixGivenTest(Main.java:108)
        at eu.stamp.project.assertfixer.Main.runWithResults(Main.java:65)
        at fr.inria.spirals.repairnator.process.step.repair.AssertFixerRepair.lambda$businessExecute$0(AssertFixerRepair.java:98)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: /root/target/dspot/TestListener.ser does not exist.
        ... 12 common frames omitted

```

**Comment by surli** [comment]
Apparently it's fixed with last changes made in AssertFixer. Thanks @danglotb
