### ISSUE TITLE
Fix expection on ComputeSourceDir: it shouldn't stop the pipeline when this step is not a blocking one.

### ISSUE THREAD

**Issue by fermadeiral** [Spirals-Team/repairnator#629]
```
23:51:08.094 [main] DEBUG f.i.s.r.p.s.paths.ComputeSourceDir - ----------------------------------------------------------------------
23:51:08.094 [main] DEBUG f.i.s.r.p.s.paths.ComputeSourceDir - STEP 3/17: ComputeSourceDir
23:51:08.095 [main] DEBUG f.i.s.r.p.s.paths.ComputeSourceDir - ----------------------------------------------------------------------
23:51:08.095 [main] DEBUG f.i.s.r.p.s.paths.ComputeSourceDir - Computing the source directory ...
23:51:08.095 [main] DEBUG f.i.s.r.p.s.paths.ComputeSourceDir - The default source directory (./workspace/prestodb/presto/361876900/src/main/java) does not exists. Try to read pom.xml to get information.
23:51:08.415 [main] DEBUG f.i.s.r.p.m.RepositoryModelResolver - Downloading https://repo1.maven.org/maven2/io/airlift/airbase/80/airbase-80.pom
23:51:08.694 [main] ERROR f.i.s.r.process.maven.MavenHelper - Error while building complete model. The raw model will be used. Error message: 1 problem was encountered while building the effective model for com.facebook.presto:presto-root:0.199-SNAPSHOT
[ERROR] Failed to determine Java version for profile java9-surefire @ io.airlift:airbase:80

23:51:09.226 [main] DEBUG f.i.s.r.p.i.ProjectInspector4Bears - Exception catch while executing steps: 
java.lang.NullPointerException: null
	at java.io.File.<init>(File.java:277)
	at fr.inria.spirals.repairnator.process.step.paths.ComputeSourceDir.searchForSourcesDirectory(ComputeSourceDir.java:83)
	at fr.inria.spirals.repairnator.process.step.paths.ComputeSourceDir.businessExecute(ComputeSourceDir.java:184)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.execute(AbstractStep.java:279)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.executeNextStep(AbstractStep.java:148)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.execute(AbstractStep.java:298)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.executeNextStep(AbstractStep.java:148)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.execute(AbstractStep.java:298)
	at fr.inria.spirals.repairnator.process.inspectors.ProjectInspector4Bears.run(ProjectInspector4Bears.java:95)
	at fr.inria.spirals.repairnator.pipeline.Launcher.mainProcess(Launcher.java:358)
	at fr.inria.spirals.repairnator.pipeline.Launcher.main(Launcher.java:366)
23:51:09.227 [main] INFO  f.i.s.repairnator.pipeline.Launcher - Inspector is finished. The process will now exit.
```

**Comment by surli** [comment]
fixed in #656
