### ISSUE TITLE
Fix exception in CommitProcessEnd: a check needs to be done on PushState to avoid the exception happens.

### ISSUE THREAD

**Issue by fermadeiral** [Spirals-Team/repairnator#630]
```
23:55:53.323 [main] DEBUG f.i.s.r.p.step.push.CommitProcessEnd - ----------------------------------------------------------------------
23:55:53.329 [main] DEBUG f.i.s.r.p.step.push.CommitProcessEnd - STEP 16/17: CommitProcessEnd
23:55:53.329 [main] DEBUG f.i.s.r.p.step.push.CommitProcessEnd - ----------------------------------------------------------------------
23:55:53.330 [main] INFO  f.i.s.r.p.step.push.CommitProcessEnd - Commit process end...
23:55:53.330 [main] DEBUG f.i.s.r.process.git.GitHelper - Copying files...
23:55:53.330 [main] DEBUG f.i.s.r.process.git.GitHelper - Source dir: ./workspace/prestodb/presto/307792549
23:55:53.331 [main] DEBUG f.i.s.r.process.git.GitHelper - Target dir: ./workspace/prestodb/presto/307792549_topush
23:55:53.337 [main] DEBUG f.i.s.r.process.git.GitHelper - File not copied: ./workspace/prestodb/presto/307792549/.git
23:55:53.338 [main] DEBUG f.i.s.r.process.git.GitHelper - File not copied: ./workspace/prestodb/presto/307792549/.gitignore
23:55:53.340 [main] DEBUG f.i.s.r.process.git.GitHelper - File not copied: ./workspace/prestodb/presto/307792549/.git
23:55:53.340 [main] DEBUG f.i.s.r.process.git.GitHelper - File not copied: ./workspace/prestodb/presto/307792549/.gitignore
23:55:56.220 [main] INFO  f.i.s.r.process.git.GitHelper - Notification block detected. The travis file will be changed.
23:55:56.228 [main] ERROR f.i.s.r.p.step.push.CommitProcessEnd - Error while opening the local git repository, maybe it has not been initialized.
org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /root/workspace/prestodb/presto/307792549_topush
	at org.eclipse.jgit.lib.BaseRepositoryBuilder.build(BaseRepositoryBuilder.java:582)
	at org.eclipse.jgit.api.Git.open(Git.java:117)
	at org.eclipse.jgit.api.Git.open(Git.java:99)
	at fr.inria.spirals.repairnator.process.step.push.CommitFiles.businessExecute(CommitFiles.java:55)
	at fr.inria.spirals.repairnator.process.step.push.CommitProcessEnd.businessExecute(CommitProcessEnd.java:20)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.execute(AbstractStep.java:279)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.executeNextStep(AbstractStep.java:148)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.execute(AbstractStep.java:298)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.terminatePipeline(AbstractStep.java:310)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.execute(AbstractStep.java:301)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.executeNextStep(AbstractStep.java:148)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.execute(AbstractStep.java:298)
	at fr.inria.spirals.repairnator.process.inspectors.ProjectInspector4Bears.run(ProjectInspector4Bears.java:95)
	at fr.inria.spirals.repairnator.pipeline.Launcher.mainProcess(Launcher.java:358)
	at fr.inria.spirals.repairnator.pipeline.Launcher.main(Launcher.java:366)
23:55:56.229 [main] DEBUG f.i.s.r.p.step.push.CommitProcessEnd - STEP STATUS: [ CommitProcessEnd : SKIPPED ( Error while initializing or opening the local git repository. ) ]
23:55:56.229 [main] DEBUG f.i.s.r.p.step.push.CommitProcessEnd - STEP DURATION: 2s
23:55:56.230 [main] DEBUG f.i.s.r.p.step.push.CommitProcessEnd - EXECUTE NEXT STEP
```

**Comment by surli** [comment]
fixed in #656
