### ISSUE TITLE
operate an instance of Repairnator on SNIC

### ISSUE THREAD

**Issue by monperrus** [Spirals-Team/repairnator#646]
this instance would:
- analyze Travis builds
- perform repair attempts
- push data in a local MongoDB
- send emails about errors

it would NOT:
- send emails about patches
- push to github

(because this is still the responsibility of the Inria instance)

Later we'll compare the results between the Inria instance and the SNIC one

**Comment by btellstrom** [comment]
I know have a login to SNIC and am able to SSH into an instance. As I've understood it, what I have to do is to fill in the options below and then run the `launch_rtscanner.sh` script on the SNIC instance. @surli anything else that need to be done? 

```
MONGODB_HOST= 
MONGODB_NAME= 
SMTP_SERVER= 
NOTIFY_TO= 
NOTIFY_ENDPROCESS=0 

WHITELIST_PATH=$HOME_REPAIR/whitelist.txt 
BLACKLIST_PATH=$HOME_REPAIR/blacklist.txt 
DURATION=PT10m
```

**Comment by surli** [comment]
Don't forget to let `DURATION` blank to run it without stop. For now it looks good, be careful to the `Versions` section in the future: you might want to use the snapshots version of repairnator in the future.

**Comment by surli** [comment]
> should I create a new one

Yes you should create a new one: we have one at INRIA but it might be deleted as of september.

> Same for SMTP

Yes indeed, but check with @monperrus and KTH for this one, it far more difficult than to setup a mongodb.

> Also, does the NOTIFY_ENDPROCESS=0 ensure that only errors are emailed? I can not see anywhere in the configuration file that would exclude patches otherwise.

No: `NOTIFY_ENDPROCESS` send an email when a process terminate normally, it really a notifier when you do some specific operations. 
The only switch off to disable error notification or patch notification is to not specify the smtp server. Else you'll always get those notifications.

**Comment by btellstrom** [comment]
Okay, thanks!

>it would NOT:
>
>    * send emails about patches

Guess that bit won't be possible then?

**Comment by surli** [comment]
> Guess that bit won't be possible then?

Indeed: I did not read it. So yeah not possible for now.
Actually for now what you can do is to only specify your email address and not Martin's one: then he won't get twice the emails. And you'll be able to change that config at the end of august when I'll stop INRIA instance. WDYT?

**Comment by btellstrom** [comment]
Sounds good. Since he still wanted the error emails I could just autoforward them to him or keep an eye on my own email.

A few more questions, how much RAM would you recommend for the instance, and I assume there is no issue with having the MONGODB in the same place as repairnator (the same instance)?

**Comment by surli** [comment]
FYI @btellstrom I'm working on #572 which might be helpful for you when your instance of Repairnator will be running. Don't hesitate to ask question on the PR (#679) if some things are not clear enough.

**Comment by surli** [comment]
@btellstrom one more info:
be careful with the disk usage of your machine, if possible creates different partition: you'll need lot of disk space for docker, and potentially also for the logs produced by Repairnator. Especially if you plan to run it on a long term view.

**Comment by btellstrom** [comment]
Okay, I'll take that into account. Was asking for the RAM because my laptop crashed when trying to run it for 10 minutes, and that should have had at least 2-3 GB of RAM free if I remember correctly.

May I ask how you determined the number of threads you were able to use? Just trial and error? Also, I assume Go means GigaByte?

**Comment by surli** [comment]
> Also, I assume Go means GigaByte?

Yes

> May I ask how you determined the number of threads you were able to use? Just trial and error?

Sadly yes: and it can also depends on the kind of projects you try to repair, so not an exact science there :-/

**Comment by btellstrom** [comment]
@surli you don't happen to have a recommended blacklist?

**Comment by surli** [comment]
Yes we have: look on https://github.com/Spirals-Team/repairnator/tree/df35734df9c2408037da9a3ede90343294788223/repairnator/repairnator-realtime/src/main/resources

Usually I do a symbolic link towards those files and I point to the symbolic link in repairnator.cfg.

**Comment by btellstrom** [comment]
@surli when will [this](http://repairnator.lille.inria.fr/) instance of repainrator stop?

**Comment by surli** [comment]
At the end of august, certainly the 30th. I'll also push a snapshot of the database at that moment. 
I think the idea of @monperrus was to have a bit of overlap to check that the results were the same between this instance and yours.

**Comment by btellstrom** [comment]
Okay. May I ask, how much disk space is the database currently occupying?

**Comment by surli** [comment]
It currently takes 22 Gb.

**Comment by btellstrom** [comment]
It is currently able to run, with the compromise being that the database and repairnator is on the same machine. It currently does not have SMTP configured.

**Comment by monperrus** [comment]
Excellent. What's the process to query the database for the latest repair attempts?

**Comment by bloriot97** [comment]
For some reasons I have trouble running the pipeline on snic.
It fails during the building of the project because of the timeout (600 sec) from maven.
```
java.lang.InterruptedException: Timeout occurred: no output has been received in the last 10 minutes.
	at fr.inria.spirals.repairnator.process.maven.MavenHelper.run(MavenHelper.java:177)
	at fr.inria.spirals.repairnator.process.step.BuildProject.businessExecute(BuildProject.java:32)
	...
```

No mater the project it is always the same issue. 

Have you ever experienced that issue using other machines @surli or @fermadeiral ?

Maven v. 3.3.9
Java  openjdk version "1.8.0_181"

**Comment by surli** [comment]
This timeout is actually brought by Repairnator, see: https://github.com/Spirals-Team/repairnator/blob/master/repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/maven/MavenHelper.java#L167

Now it shouldn't happen for all builds. You might want to run it in debug to see what happens here.

**Comment by fermadeiral** [comment]
> Have you ever experienced that issue using other machines @surli or @fermadeiral ?

@bloriot97 a lot in fact. But maybe you are running with the "problematic" projects.
Try this build: 351742666 (from SzFMV2018-Tavasz-AutomatedCar). If even for this project this happens, thus...

**Comment by surli** [comment]
Did you try just cloning a project and running a mvn command on it, to see what happens?

> I don't know if it is due to a slow network, to a poor computational power or anything else but I always have the issue on SNIC, I ran the scanner for more than 24 hours and I think that every build ran out of time.

No, the examples should work even on a rasp :) 
You might have a connection issue though, like dependency that won't download and block the builds, things like that. Trying doing it manually to see.
