### ISSUE TITLE
On the timeout for maven goal.

### ISSUE THREAD

**Issue by fermadeiral** [Spirals-Team/repairnator#737]
When running 4 builds from spoon triggered in the last days, I got the exit status "not testable" due to the timeout of 10 minutes reached when testing with maven. Maybe this timeout is too low?

**Comment by monperrus** [comment]
Spoon's test suite now takes more than 10 minutes (a lot of strong tests :)

Do you mean the repairnator's timeout or bear's one?

**Comment by fermadeiral** [comment]
> Spoon's test suite now takes more than 10 minutes (a lot of strong tests :)

Nice!

> Do you mean the repairnator's timeout or bear's one?

The timeout is the same for both. IF Repairnator is reproducing spoon builds right now is because the failure happens before the timeout to be reached. In the case of Bears, the entire test suite is executed when we have a patched build, thus the timeout happens. I got 4 in the last few days, all of them due to the 10-minute timeout when testing.

**Comment by fermadeiral** [comment]
I checked this issue closer, and apparently it's ok. The 10-minute timeout is a timeout for no output. Check out the beginning of this log, for instance:

```
18:08:14.362 [Thread-8] DEBUG f.i.s.r.p.m.o.MavenFilterOutputHandler - [INFO] Running spoon.test.main.MainTest
18:18:15.061 [main] ERROR f.i.s.r.process.step.TestProject - Error while testing the project.
java.lang.InterruptedException: Timeout occurred: no output has been received in the last 10 minutes.
	at fr.inria.spirals.repairnator.process.maven.MavenHelper.run(MavenHelper.java:167)
	at fr.inria.spirals.repairnator.process.step.TestProject.businessExecute(TestProject.java:34)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.execute(AbstractStep.java:334)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.executeNextStep(AbstractStep.java:187)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.execute(AbstractStep.java:351)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.executeNextStep(AbstractStep.java:187)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.execute(AbstractStep.java:351)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.executeNextStep(AbstractStep.java:187)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.execute(AbstractStep.java:351)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.executeNextStep(AbstractStep.java:187)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.execute(AbstractStep.java:351)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.executeNextStep(AbstractStep.java:187)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.execute(AbstractStep.java:351)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.executeNextStep(AbstractStep.java:187)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.execute(AbstractStep.java:351)
	at fr.inria.spirals.repairnator.process.inspectors.ProjectInspector4Bears.run(ProjectInspector4Bears.java:104)
	at fr.inria.spirals.repairnator.pipeline.Launcher.mainProcess(Launcher.java:378)
	at fr.inria.spirals.repairnator.pipeline.Launcher.main(Launcher.java:386)
18:18:15.062 [main] DEBUG f.i.s.r.process.step.TestProject - STEP STATUS: [ TestProjectBuggyBuildCandidateSourceCode : FAILURE ( NOTTESTABLE ) ]
```

Thus the timeout choice seems good, yet I don't understand why I'm always having this issue with spoon in the last days, i.e. why I do not get output when testing for 10 minutes.

I propose to close this issue.

**Comment by surli** [comment]
>  [INFO] Running spoon.test.main.MainTest

MainTest is one of the biggest (and longest) test of Spoon, so it might make sense that it take more than 10 minutes to be executed, depending on your machine and what you're doing.

**Comment by fermadeiral** [comment]
> MainTest is one of the biggest (and longest) test of Spoon, so it might make sense that it take more than 10 minutes to be executed, depending on your machine and what you're doing.

I thought about that too. I don't think the machine is the issue, because I'm using bears machine, which is not like my laptop :-) but it's probably the second thing you said (the processing being done).

**Comment by bloriot97** [comment]
I had the same issue with the 2 last pr I intended.

**Comment by fermadeiral** [comment]
> I had the same issue with the 2 last pr I intended.

Hi @bloriot97. Welcome in this project! This issue is not related to what has happened in your PRs. Actually this issue was already discussed thus I'm closing it now.
