### ISSUE TITLE
The realtime scanner stopped after an unexpected error this morning. 

### ISSUE THREAD

**Issue by bloriot97** [Spirals-Team/repairnator#791]
Hey this morning the realtime scanner stopped running properly after it got this error : 
```
Exception in thread "Thread-2" java.lang.NumberFormatException: null
        at java.lang.Integer.parseInt(Integer.java:542)
        at java.lang.Integer.parseInt(Integer.java:615)
        at fr.inria.jtravis.parsers.MavenLogParser.parseTestLine(MavenLogParser.java:52)
        at fr.inria.jtravis.parsers.MavenLogParser.advancedParseLog(MavenLogParser.java:102)
        at fr.inria.jtravis.parsers.MavenLogParser.parseLog(MavenLogParser.java:67)
        at fr.inria.jtravis.parsers.LogParser.getTestsInformation(LogParser.java:113)
        at fr.inria.jtravis.entities.Log.getTestsInformation(Log.java:52)
        at fr.inria.spirals.repairnator.realtime.RTScanner.isRepositoryInteresting(RTScanner.java:261)
        at fr.inria.spirals.repairnator.realtime.InspectJobs.run(InspectJobs.java:47)
        at java.lang.Thread.run(Thread.java:748)
``` 
After this error the RT-scanner was not able to retrieve failing builds and it was only logging this (with a decreasing number of builds down to 0, they were most likely sent to the pipeline).
```
[Thread-1] INFO  f.i.s.r.realtime.InspectBuilds - Refresh all inspected build status (nb builds: 4)
```
I was not able to find what was the faulty travis build, but I think this is probably related to an unhandled exception in JTravis, @surli WDYT ?

**Comment by monperrus** [comment]
Simon, do you plan to fix it yourself? Thanks! --Martin

**Comment by surli** [comment]
yep
