### ISSUE TITLE
Repairnator faces issues during the build .

### ISSUE THREAD

**Issue by bloriot97** [Spirals-Team/repairnator#802]
For some reasons repairnator always fails when it tries to build a project.
From what I have seen we always get the same error message:

```
19:47:46.232 [Thread-6] ERROR f.i.s.r.p.m.output.MavenErrorHandler - Exception in thread "main" java.lang.NoClassDefFoundError: com/google/inject/spi/Elements$RecordingBinder
19:47:46.233 [Thread-6] ERROR f.i.s.r.p.m.output.MavenErrorHandler - 	at com.google.inject.spi.Elements.getElements(Elements.java:108)
19:47:46.233 [Thread-6] ERROR f.i.s.r.p.m.output.MavenErrorHandler - 	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
19:47:46.233 [Thread-6] ERROR f.i.s.r.p.m.output.MavenErrorHandler - 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
19:47:46.233 [Thread-6] ERROR f.i.s.r.p.m.output.MavenErrorHandler - 	at com.google.inject.Guice.createInjector(Guice.java:96)
19:47:46.234 [Thread-6] ERROR f.i.s.r.p.m.output.MavenErrorHandler - 	at com.google.inject.Guice.createInjector(Guice.java:73)
19:47:46.234 [Thread-6] ERROR f.i.s.r.p.m.output.MavenErrorHandler - 	at com.google.inject.Guice.createInjector(Guice.java:62)
19:47:46.234 [Thread-6] ERROR f.i.s.r.p.m.output.MavenErrorHandler - 	at org.codehaus.plexus.DefaultPlexusContainer.addPlexusInjector(DefaultPlexusContainer.java:481)
19:47:46.234 [Thread-6] ERROR f.i.s.r.p.m.output.MavenErrorHandler - 	at org.codehaus.plexus.DefaultPlexusContainer.<init>(DefaultPlexusContainer.java:206)
19:47:46.234 [Thread-6] ERROR f.i.s.r.p.m.output.MavenErrorHandler - 	at org.apache.maven.cli.MavenCli.container(MavenCli.java:545)
19:47:46.235 [Thread-6] ERROR f.i.s.r.p.m.output.MavenErrorHandler - 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:281)
19:47:46.235 [Thread-6] ERROR f.i.s.r.p.m.output.MavenErrorHandler - 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
19:47:46.235 [Thread-6] ERROR f.i.s.r.p.m.output.MavenErrorHandler - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
19:47:46.235 [Thread-6] ERROR f.i.s.r.p.m.output.MavenErrorHandler - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
19:47:46.235 [Thread-6] ERROR f.i.s.r.p.m.output.MavenErrorHandler - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19:47:46.235 [Thread-6] ERROR f.i.s.r.p.m.output.MavenErrorHandler - 	at java.lang.reflect.Method.invoke(Method.java:498)
19:47:46.235 [Thread-6] ERROR f.i.s.r.p.m.output.MavenErrorHandler - 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
19:47:46.235 [Thread-6] ERROR f.i.s.r.p.m.output.MavenErrorHandler - 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
19:47:46.236 [Thread-6] ERROR f.i.s.r.p.m.output.MavenErrorHandler - 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
19:47:46.236 [Thread-6] ERROR f.i.s.r.p.m.output.MavenErrorHandler - 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
19:47:46.236 [Thread-6] ERROR f.i.s.r.p.m.output.MavenErrorHandler - Caused by: java.lang.ClassNotFoundException: com.google.inject.spi.Elements$RecordingBinder
19:47:46.236 [Thread-6] ERROR f.i.s.r.p.m.output.MavenErrorHandler - 	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
19:47:46.236 [Thread-6] ERROR f.i.s.r.p.m.output.MavenErrorHandler - 	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
19:47:46.236 [Thread-6] ERROR f.i.s.r.p.m.output.MavenErrorHandler - 	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
19:47:46.236 [Thread-6] ERROR f.i.s.r.p.m.output.MavenErrorHandler - 	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
19:47:46.236 [Thread-6] ERROR f.i.s.r.p.m.output.MavenErrorHandler - 	... 19 more
```

I have restarted it but we keep having the same issue, do you have any idea of what could cause this?

**Comment by monperrus** [comment]
Fixed by rebuiblind the docker image of the pipeline. Repairnator is running again.
